// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://erwlnexwbrvvnvxtkeqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyd2xuZXh3YnJ2dm52eHRrZXFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNjg0NjcsImV4cCI6MjA2NDk0NDQ2N30.-210JoAjPrEKWMk-8Yedc7A4J-g0BhS9hvn1Sap5mz4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);